package router

import (
	"fmt"
	"net/url"

	"github.com/inhandnet/inconnect-cli/internal/factory"
	"github.com/inhandnet/inconnect-cli/internal/iostreams"
	"github.com/spf13/cobra"
)

func newCmdConfigSend(f *factory.Factory) *cobra.Command {
	return &cobra.Command{
		Use:   "config-send <id>",
		Short: "Push the platform-rendered VPN config (certs/CA/firewall) to a router",
		Long: `Have the platform render this router's VPN (OpenVPN) config — device
certificate, private key, CA, and firewall rules — and push it to the device.

The content is generated by the platform from the device model template; you
do NOT supply any config content. Works while the device is offline (the task
queues and applies once it reconnects).

This is VPN-specific. To push an arbitrary full device config that you supply,
use "router device-config set" instead.`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			client, err := f.APIClient()
			if err != nil {
				return err
			}

			q := url.Values{}
			if oid, _ := cmd.Flags().GetString("oid"); oid != "" {
				q.Set("oid", oid)
			}

			body, err := client.Get("/api/invpn/router/"+args[0]+"/config/send", q)
			if err != nil {
				if body != nil {
					_ = iostreams.FormatOutput(body, f.IO, f.IO.Output)
				}
				return err
			}

			fmt.Fprintf(f.IO.ErrOut, "Config push triggered for router %s\n", args[0])
			return iostreams.FormatOutput(body, f.IO, f.IO.Output)
		},
	}
}
